arch: efficientdet_d0
model_params:
    # pretrained: null
    pretrained: "coco"
    # only needed to test that per epoch val is working. disable for training
    match_tf_same_padding: True
    # want to unfreeze encoder because batch is large enough
    encoder_norm_layer: frozenabn # abn
    # as in effdet. but need to check that i really have 90 classes not 80 
    num_classes: 90
short_epoch: True
optim : fused_sgd
size: 512
batch_size: 16
phases : [{"ep": [0, 2], "lr": [0, 0], "mom": 0.9}]